coverage:
  status:
    project:
      default:
        # basic
        target: 90%
        threshold: null
        base: auto
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths:
          libratom
        ignore:
          "libratom/scripts/download_edrm_zipped_files.py"
    patch:
      default:
        # basic
        target: 85%
        threshold: null
        base: auto
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths:
          libratom
        ignore:
          "libratom/scripts/download_edrm_zipped_files.py"
