name: Publish to PYPI

on:
  push:
    branches:
      - master
      - publish
    tags:
      - '*'

jobs:
  publish:
    name: Build a distribution and upload it to PYPI
    runs-on: ubuntu-20.04
    if: github.repository_owner == 'libratom'  # So that it doesn't run on forks
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'  # PBR needs commit and tag history to set version
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements-dev.txt
      - name: Build
        run: python setup.py sdist bdist_wheel
      - name: Test Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
#      - name: Publish
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          user: __token__
#          password: ${{ secrets.PYPI_API_TOKEN }}
#          skip_existing: true
