name: Build And Test

on:
  - push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      EDRM_DIR: /tmp/libratom/test_data/RevisedEDRMv1_Complete
    strategy:
      matrix:
#        os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v2
    - name: Download Enron data from github storage
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: cache_test_data.yml
        path: ${{ env.EDRM_DIR }}
    - name: Check local data dir
      run: ls -al ${{ env.EDRM_DIR }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Run test suite (tox)
      run: tox
